### ISSUE TITLE
Lots of unnecessary files in repository

### ISSUE THREAD

**Issue by Choonster** [LapisSea/Magiology_1.8#1]
I just stumbled across this repository while searching for uses of Forge's new capability system and noticed you have the Minecraft source code (including Forge's capability patches) in the **build** directory. This doesn't need to be in the repository and it probably violates Minecraft's EULA to have it here.

These directories and files don't need to be part of the repository as they're either useless on their own or can be automatically generated:
* Temporary files/compiled classes: **.gradle/**, **build/**, **out/**
* IDE projects: **eclipse/**, **Magiology 1.8.iml**/**.ipr**/**.iws**
* Minecraft game directory: **run/**

I'd suggest adding a **.gitignore** file like [this one](https://github.com/diesieben07/SevenCommons/blob/06d22dc1a0a16465aa0b3069a78e8effab42e934/.gitignore). This tells Git to ignore everything (first two lines) except the whitelisted directories and files (lines starting with a `!`).

You can remove newly-ignored existing files from the repository by running `git rm --cached *` followed by `git add *` (i.e. remove everything from the index, then add everything to the index that's not ignored).

If you want to completely remove the ignored files from the repository's history, you can follow the instructions [here](http://gitready.com/beginner/2009/03/06/ignoring-doesnt-remove-a-file.html).

**Comment by LapisSea** [comment]
Huh thanks a lot! I always wanted to get in to the gitignore but I never had the time to understand it. People always give complicated formats so I always back up.
I will clean it up shortly! :)

**Comment by LapisSea** [comment]
So I did that and files are ignored. I created a test folder and test file and it is indeed ignored. But I can't seem to remove the ignored files on the server.

**Comment by LapisSea** [comment]
Ok nevermind! I forgot to sync! I am a derp....
